# Generated by Django 4.2 on 2024-06-23 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sent by'),
        ),
        migrations.AddField(
            model_name='comment_like_list',
            name='news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news_module.news_comments', verbose_name='parent news'),
        ),
        migrations.AddField(
            model_name='comment_like_list',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='users list'),
        ),
        migrations.AddField(
            model_name='comment_dislike_list',
            name='news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news_module.news_comments', verbose_name='parent news'),
        ),
        migrations.AddField(
            model_name='comment_dislike_list',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='users list'),
        ),
    ]
