# Generated by Django 4.2 on 2024-06-23 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messages_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_groups',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='groups users'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messages_module.message_groups', verbose_name='parent message group'),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sent by who'),
        ),
    ]
