# Generated by Django 4.2 on 2024-07-10 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_module', '0006_remove_post_model_hashtags_hash_tag_posts'),
        ('messages_module', '0004_message_seen_list_message_seen_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Forwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('desc', models.TextField(blank=True, max_length=500, null=True, verbose_name='posts description')),
            ],
        ),
        migrations.RemoveField(
            model_name='direct_message_group',
            name='users',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attached_post',
        ),
        migrations.AddField(
            model_name='message_groups',
            name='group_type',
            field=models.CharField(choices=[('normal', 'normal'), ('direct', 'direct')], default='normal', max_length=10, verbose_name='type of group'),
        ),
        migrations.DeleteModel(
            name='Direct_Message',
        ),
        migrations.DeleteModel(
            name='Direct_Message_Group',
        ),
        migrations.AddField(
            model_name='post_forwards',
            name='parent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messages_module.message_groups', verbose_name='which group does this message belong to'),
        ),
        migrations.AddField(
            model_name='post_forwards',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_module.post_model', verbose_name='attached post'),
        ),
        migrations.AddField(
            model_name='post_forwards',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='who sent this post'),
        ),
    ]
