# Generated by Django 4.2 on 2024-07-16 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages_module', '0005_post_forwards_remove_direct_message_group_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_forwards',
            name='seen_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messages_module.message_seen_list'),
        ),
    ]
