# Generated by Django 4.2 on 2024-06-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_type', models.CharField(choices=[('gun_skin', 'gun_skin'), ('character', 'character'), ('gun', 'gun'), ('outfit', 'outfit')], default='gun_skin', max_length=15, verbose_name='product type')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='price of product')),
                ('is_availible', models.BooleanField(default=True, verbose_name='product_availblity')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date of creation')),
                ('product_name', models.CharField(default='', max_length=100, verbose_name='name of the product')),
                ('multiple', models.BooleanField(default=True, verbose_name='is user allowed to have multiple instances of this product?')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='product description')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200, verbose_name='comments text')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='image file')),
            ],
        ),
        migrations.CreateModel(
            name='Product_List_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='how many')),
            ],
        ),
        migrations.CreateModel(
            name='User_Bought_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
