# Generated by Django 4.2 on 2024-06-23 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bought_products',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner of this list'),
        ),
        migrations.AddField(
            model_name='product_list_detail',
            name='parent_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.user_bought_products', verbose_name='parent list of details'),
        ),
        migrations.AddField(
            model_name='product_list_detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='product_image',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='parent product'),
        ),
        migrations.AddField(
            model_name='product_comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.product_comment', verbose_name='parent comment'),
        ),
        migrations.AddField(
            model_name='product_comment',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='parent product'),
        ),
        migrations.AddField(
            model_name='product_comment',
            name='wrote_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='who wrote this comment'),
        ),
    ]
