# Generated by Django 4.2 on 2024-06-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField(max_length=2000, verbose_name='main text')),
                ('attached_file', models.ImageField(blank=True, null=True, upload_to='report_files', verbose_name='reports attached file')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='when was this report written')),
                ('is_reply', models.BooleanField(default=False, verbose_name='is this a reply message')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='session title')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='date of session creation')),
            ],
        ),
    ]
