# Generated by Django 4.2 on 2024-06-23 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator of this post'),
        ),
        migrations.AddField(
            model_name='post_images',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_module.post_model', verbose_name='parent post'),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_module.post_model', verbose_name='parent post'),
        ),
        migrations.AddField(
            model_name='post_comment',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
