# Generated by Django 4.2 on 2024-06-28 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_module', '0003_post_comment_parent_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Like_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post_module.post_model', verbose_name='parent post of list')),
                ('users', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='users that liked this post')),
            ],
        ),
    ]
