# Generated by Django 4.2 on 2024-07-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0005_hash_tag_alter_post_like_list_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='hash_tag',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, to='post_module.post_model', verbose_name='related posts'),
        ),
    ]
